[package]
name = "AdventOfCode"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "aoc2015",
    "aoc2021",
    "aoc2022",
    "aoc2023",
    "aoc2024",
    "aoc2025",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
