[package]
name = "aoc2015"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
regex = "1.5.4"
ndarray = "0.15.4"
lazy_static = "1.4.0"
